import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import assert from 'node:assert/strict';
async function load(path) {
  const code = stripTypeScriptTypes(readFileSync(path, 'utf8'), { mode: 'transform' });
  return import('data:text/javascript;base64,' + Buffer.from(code).toString('base64'));
}
const { SpikeDetector, spikeSettings } = await load('src/spike-detector.ts');
const { GainStage } = await load('src/gain.ts');
const detector = new SpikeDetector();
for (let i = 0; i < 40; i++) assert.equal(detector.update(-30, 50), 0);
assert.equal(detector.update(-18, 50), 12);
for (let i = 0; i < 100; i++) assert.equal(detector.update(-18, 50), 12);
for (let i = 0; i < 5; i++) assert.equal(detector.update(-30, 50), 12);
assert.equal(detector.update(-30, 50), 0);
const gradual = new SpikeDetector();
for (let i = 0; i < 40; i++) gradual.update(-40, 50);
for (let db = -39; db < -10; db++) assert.equal(gradual.update(db, 50), 0);
const silent = new SpikeDetector();
for (let i = 0; i < 40; i++) assert.equal(silent.update(null, 50), 0);
assert.equal(silent.update(-10, 50), 0);
const sensitive = new SpikeDetector({ ...spikeSettings, thresholdDb: 5 });
for (let i = 0; i < 40; i++) sensitive.update(-30, 50);
assert.equal(sensitive.update(-24, 50), 6);
assert.equal(sensitive.update(0, 50), 18);
assert.throws(() => new SpikeDetector({ ...spikeSettings, thresholdDb: -1 }));
const ramps = [];
const node = { gain: { value: 1, cancelAndHoldAtTime() {}, linearRampToValueAtTime: (v,t) => ramps.push([v,t]) }, disconnect() {} };
const gain = new GainStage({ currentTime: 1, createGain: () => node });
gain.setVolume(0.5);
gain.setReduction(12);
assert.ok(Math.abs(ramps.at(-1)[0] - 0.5 * 10 ** (-12/20)) < 1e-12);
assert.equal(ramps.at(-1)[1], 1.04);
const count = ramps.length;
gain.setReduction(12);
assert.equal(ramps.length, count);
gain.setReduction(0);
assert.deepEqual(ramps.at(-1), [0.5, 2.2]);
gain.setVolume(0);
gain.setReduction(12);
assert.equal(ramps.at(-1)[0], 0);
console.log('PASS: stable baseline, spike, sustained loudness, recovery hold, gradual rise, silence, threshold, reduction cap, attack/release, manual mute');
